# Generated by Django 4.0.3 on 2022-06-28 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('software engineering', 'SOFTWARE ENGINEERING'), ('networking', 'NETWORKING'), ('information management', 'INFORMATION MANAGEMENT'), ('data science', 'DATA SCIENCE')], max_length=100)),
                ('facultyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.faculty')),
            ],
        ),
    ]
