# Generated by Django 4.0.3 on 2022-06-28 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('dob', models.DateTimeField()),
                ('address', models.CharField(max_length=100)),
                ('departmentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.department')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(choices=[('java', 'JAVA'), ('web design', 'WEB DESIGN'), ('big data', 'BIG DATA'), ('tcp/ip', 'TCP/IP'), ('data structure', 'DATA STRUCTURE'), ('linux', 'LINUX'), ('web tech', 'WEB TECH')], max_length=100)),
                ('courseDept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.department')),
            ],
        ),
    ]
